_welcome:
    pattern:  /
    defaults: { _controller: RestManApiBundle:Default:index }


restaurants:
    resource: "@RestManApiBundle/Controller/RestaurantsController.php"
    type:     annotation
    defaults: {_format: html}
    requirements:
        _format: json|html|pdf
