rest_man_api_homepage:
    path:     /hello/{name}
    defaults: { _controller: RestManApiBundle:Default:index }

restaurants:
    resource: "@RestManApiBundle/Controller/RestaurantsController.php"
    type:     annotation
    prefix:   /restaurants
