<?php

namespace RestMan\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RestaurantDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantDetailRepository extends EntityRepository
{
}
