<?php

namespace RestMan\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLikeRepository extends EntityRepository
{
}
